name=MicroLog
version=1.0.0
author=Thomas O Fredericks <thomas@fredericks.info> 
maintainer=Thomas O Fredericks <thomas@fredericks.info>
sentence=Arduino logging library
paragraph=A small (micro) library to help with logging through a Stream (like Serial)
category=Communication
url=https://github.com/thomasfredericks/MicroLog
includes=MicroLog.h
architectures=*
