[platformio]
; Tell PIO to treat this folder (containing .ino) as the source directory
src_dir = .

[env:nano_r4]
platform = renesas-ra
board = nano_r4
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/thomasfredericks/MicroLog

